name: Bryan Rowland
favicon: null
layout_spectrum: 0
typography_spectrum: 0.16285
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f8f8f8'
    - '#2a2829'
    - '#696661'
    - '#d9bd96'
  brandStrength: 0.13042691396549344
  lightness: 0.329584033228457
  saturation: 0.35276241274550557
  rhythmicContrast: 0.9417176798451692
purpose: []
